### ISSUE TITLE
[Watcher] - Monitoring signers update

### ISSUE THREAD

**Issue by imqdee** [LedgerHQ/ledger-fresh-management#46]
## Header

**Name of the task**: Monitoring signers update

**Name of the module**: Module Watcher

**Difficulty**: 5

**Waiting for**: #44 #45

### Short description

Now that we monitor and store the deployment of each new smart-contract wallet, we want to track the modification of the signers for each wallet.

### Full description

In terms of UX, it is fundamental for us to know which wallet is associated with the signer that the user used to connect to our application. The signer and the wallet are the same entity in a non-AA environment. Now that we have separated the two entities thanks to the account abstraction, it is more difficult to know which accounts you can interact with. That's why for UX purposes we need a mapping between the public keys authorized by the contract account and the account address.

However, to do that, we have to monitor each wallet deployed by our deployer and react to the signer update events. Here's the list of subtasks that must be done to complete this task:

- [ ] Until now, we only listened to events from the deployer. It is not enough for our use cases as signer update events are triggered by the smart-contract wallet. Update the current implementation done in #45 to include, in real-time, all deployed accounts to the watch list of Apibara
- [ ] Configure the watching of all deployed smart-contract accounts to react properly to the events triggered by the modification of the signer list. These events are described below.
- [ ] Take care of the initialization process. When the watcher developed in #45 restarts, the first action must be fetching the list of wallet addresses from the database detailed in #44 in order to correctly set up the watching list using Apibara.

Here are the events that must be listened to track signers update:

```cairo
// signer is a pubkey

@event
func signer_add(
    wallet_address: felt, signer: felt
) {}

@event
func signer_remove(
    wallet_address: felt, signer: felt
) {}
```

Here's the action that must be taken for each event:

- [ ] Every time a `signer_add` event is triggered, the watcher must update the entry of the wallet address concerned in the database defined in #44 and include the signer to the list of the associated signer
- [ ] Every time a `signer_remove` event is triggered, the watcher must update the entry of the wallet address concerned in the database defined in #44 and remove the signer from the list of the associated signer

Everything must be tested, prettied, eslinted and the README of the repository should describe the API.

### Additionals ressources

- [Apibara](https://www.apibara.com/)
- [Apibara typescript SDK](https://www.apibara.com/docs/typescript-sdk)
- [Starknet events](https://starknet.io/docs/hello_starknet/events.html)
