### ISSUE TITLE
[Watcher] - Save the last processed block id

### ISSUE THREAD

**Issue by imqdee** [LedgerHQ/ledger-fresh-management#48]
## Header

**Name of the task**: Save last processed block id

**Name of the module**: Watcher

**Difficulty**: 3

**Waiting for**: #44 #45 #46 #47

### Short description

In order to not miss a block because the server shut down, restarts, or anything else, we need to know what the last block proceed by the server. The id of a block would be saved after the block has been proceeded by the server. It will be used as the starting id when the server restarts to be sure to proceed with blocks missed during the time when the server was down.

### Full description

If the processing of a block goes well (meaning there are no unexpected errors), the last step before processing the new one would be to store the id of the block in a database. Here's the subtask that must be done in order to complete this task:

- [ ] Update the database created in #44 in order to add a variable that will store an int called. Here's a minimalist schema:

```typescript
type LastBlockID = number;
```

- [ ] Extend the logic developed in #45 #46 #47 in order to send an UPDATE request to the database configured in #44 if the processing goes well. The id of the block processed would be passed as a parameter of the request. You have to use the same ORM used in #47

- [ ] Extend the initialization logic developed in #47 in order to start the synchronization at the id fetched from the database. Parallelize the block id request with the wallet address request already implemented by #47. The value 0 is the default value.

### Additionals ressources

- [Apibara](https://www.apibara.com/)
- [Apibara typescript SDK](https://www.apibara.com/docs/typescript-sdk)
